import { z } from "zod";
import type { ToolDef } from "../types.js";

export const categoryTools: ToolDef[] = [
  {
    name: "list_categories",
    title: "Listar categorias",
    description: "Lista as categorias e subcategorias do usuário.",
    method: "GET",
    path: "/api/categories",
    input: {},
    readOnly: true,
  },
  {
    name: "create_category",
    title: "Criar categoria",
    description: "Cria uma categoria ou subcategoria (informe parentId para subcategoria).",
    method: "POST",
    path: "/api/categories",
    input: {
      name: z.string(),
      type: z.string().describe("EXPENSE ou INCOME"),
      icon: z.string().optional(),
      color: z.string().optional().describe("Cor hex, ex: #3B82F6"),
      parentId: z.string().optional(),
      globalCategoryId: z.string().optional(),
      globalSubcategoryId: z.string().optional(),
    },
  },
  {
    name: "update_category",
    title: "Atualizar categoria",
    description: "Atualiza campos de uma categoria (parcial — campo vazio mantém o valor atual).",
    method: "PUT",
    path: "/api/categories/:id",
    input: {
      id: z.string(),
      name: z.string().optional(),
      type: z.string().optional(),
      icon: z.string().optional(),
      color: z.string().optional(),
      parentId: z.string().optional(),
    },
  },
  {
    name: "delete_category",
    title: "Excluir categoria",
    description: "Exclui uma categoria.",
    method: "DELETE",
    path: "/api/categories/:id",
    input: { id: z.string() },
    destructive: true,
  },
  {
    name: "list_cost_centers",
    title: "Listar centros de custo",
    description: "Lista os centros de custo do usuário.",
    method: "GET",
    path: "/api/cost-centers",
    input: {},
    readOnly: true,
  },
  {
    name: "create_cost_center",
    title: "Criar centro de custo",
    description: "Cria um centro de custo.",
    method: "POST",
    path: "/api/cost-centers",
    input: { name: z.string(), icon: z.string().optional(), color: z.string().optional() },
  },
  {
    name: "update_cost_center",
    title: "Atualizar centro de custo",
    description: "Atualiza um centro de custo.",
    method: "PUT",
    path: "/api/cost-centers/:id",
    input: { id: z.string(), name: z.string().optional(), icon: z.string().optional(), color: z.string().optional() },
  },
  {
    name: "delete_cost_center",
    title: "Excluir centro de custo",
    description: "Exclui um centro de custo (não permite excluir o centro de custo padrão).",
    method: "DELETE",
    path: "/api/cost-centers/:id",
    input: { id: z.string() },
    destructive: true,
  },
];
