import { z } from "zod";
import type { ToolDef } from "../types.js";

// --- Shapes de saída (espelham as queries de goals/budgets/debts.husk + schema Prisma) ---

const countShape = z.object({
  count: z.number().optional(),
});

const goalShape = z.object({
  id: z.string().optional(),
  userId: z.string().optional(),
  name: z.string().optional(),
  targetAmount: z.number().optional(),
  currentAmount: z.number().optional(),
  deadline: z.string().optional().nullable(),
  category: z.string().optional(),
  color: z.string().optional(),
  currency: z.string().optional(),
  createdAt: z.string().optional(),
  updatedAt: z.string().optional(),
});

const budgetShape = z.object({
  id: z.string().optional(),
  userId: z.string().optional(),
  name: z.string().optional(),
  type: z.enum(["INCOME", "EXPENSE", "INVESTMENT"]).optional(),
  category: z.string().optional().nullable(),
  amount: z.number().optional(),
  currency: z.string().optional(),
  period: z.enum(["MONTHLY", "YEARLY"]).optional(),
  year: z.number().optional(),
  month: z.number().optional().nullable(),
  createdAt: z.string().optional(),
  updatedAt: z.string().optional(),
});

const budgetComparisonShape = z.object({
  budget: budgetShape.optional(),
  budgeted: z.number().optional(),
  spent: z.number().optional(),
  remaining: z.number().optional(),
  percentage: z.number().optional(),
  transactions: z.number().optional(),
  daily: z
    .array(
      z.object({
        date: z.string().optional(),
        label: z.string().optional(),
        spent: z.number().optional(),
        projected: z.number().optional().nullable(),
      }),
    )
    .optional(),
});

const debtShape = z.object({
  id: z.string().optional(),
  userId: z.string().optional(),
  name: z.string().optional(),
  totalAmount: z.number().optional(),
  remainingAmount: z.number().optional(),
  interestRate: z.number().optional().nullable(),
  dueDate: z.string().optional(),
  creditor: z.string().optional().nullable(),
  description: z.string().optional().nullable(),
  status: z.enum(["ACTIVE", "PAID", "OVERDUE"]).optional(),
  currency: z.string().optional(),
  category: z.string().optional().nullable(),
  equityId: z.string().optional().nullable(),
  createdAt: z.string().optional(),
  updatedAt: z.string().optional(),
});

export const goalBudgetDebtTools: ToolDef[] = [
  {
    name: "list_goals",
    title: "Listar metas",
    description: "Lista as metas financeiras (Goal) do usuário, mais recentes primeiro. Para progresso/prazo/aporte mensal necessário de cada meta use goal_projections (insights.ts), que já cruza essas metas com a projeção de fluxo de caixa.",
    method: "GET",
    path: "/api/goals",
    input: {},
    readOnly: true,
    outputSchema: z.object({ data: z.array(goalShape) }),
  },
  {
    name: "create_goal",
    title: "Criar meta",
    description: "Cria uma meta financeira (ex: 'Viagem', 'Reserva de emergência'). `category` e `color` são obrigatórios no banco — se omitidos, a meta é criada com esses campos vazios (string ''), então prefira sempre informá-los. Não dispara recalculo de analytics/insights (diferente de create_budget/create_debt).",
    method: "POST",
    path: "/api/goals",
    input: {
      name: z.string().describe("Nome/título da meta"),
      targetAmount: z.number().describe("Valor alvo a ser atingido"),
      currentAmount: z.number().optional().describe("Valor já acumulado hoje. Default: 0"),
      deadline: z.string().optional().describe("Prazo da meta (data ISO, ex: YYYY-MM-DD). Default: sem prazo (null)"),
      category: z.string().optional().describe("Categoria/tipo da meta (texto livre, ex: 'Viagem', 'Casa'). Campo obrigatório no banco — omitir grava string vazia"),
      color: z.string().optional().describe("Cor de exibição (hex, ex: '#22C55E'). Campo obrigatório no banco — omitir grava string vazia"),
      currency: z.string().optional().describe("Moeda (ISO 4217, ex: 'BRL'). Default: BRL"),
    },
    outputSchema: goalShape,
  },
  {
    name: "update_goal",
    title: "Atualizar meta",
    description: "Atualiza uma meta (parcial — campos omitidos ou string vazia mantêm o valor atual). Diferente de create_goal, devolve apenas `{ count }` (1 se atualizou, 0 se o id não existe ou não pertence ao usuário), não a meta atualizada — use list_goals para conferir o resultado.",
    method: "PUT",
    path: "/api/goals/:id",
    input: {
      id: z.string().describe("Id da meta (Goal) a atualizar"),
      name: z.string().optional(),
      targetAmount: z.number().optional(),
      currentAmount: z.number().optional().describe("Novo valor acumulado — útil para registrar um aporte manual na meta"),
      deadline: z.string().optional().describe("Novo prazo (data ISO). Envie string vazia não remove o prazo — não há como limpar deadline por esta tool"),
      category: z.string().optional(),
      color: z.string().optional(),
      currency: z.string().optional(),
    },
    outputSchema: countShape,
  },
  {
    name: "delete_goal",
    title: "Excluir meta",
    description: "Exclui permanentemente uma meta do usuário. Não afeta transações já vinculadas a ela (Transaction.goalId fica órfão).",
    method: "DELETE",
    path: "/api/goals/:id",
    input: { id: z.string().describe("Id da meta (Goal) a excluir") },
    destructive: true,
    outputSchema: countShape,
  },

  {
    name: "list_budgets",
    title: "Listar orçamentos",
    description: "Lista orçamentos (Budget) do usuário, mais recentes primeiro. Sem filtro retorna todos os períodos já criados (não só o mês atual). Cada item é o valor orçado; para orçado x gasto real de um orçamento específico use budget_comparison — para ver isso por categoria em todas as categorias de uma vez sem precisar de um Budget cadastrado, use categories_insights (insights.ts).",
    method: "GET",
    path: "/api/budgets",
    input: {
      year: z.string().optional().describe("Filtra por ano (ex: '2026'). Se omitido junto com month, lista todos os anos"),
      month: z.string().optional().describe("Filtra por mês (1-12). Só faz sentido combinado com year; orçamentos com period YEARLY não têm month"),
    },
    readOnly: true,
    outputSchema: z.object({ data: z.array(budgetShape) }),
  },
  {
    name: "create_budget",
    title: "Criar orçamento",
    description: "Cria um orçamento (limite planejado) por categoria e período. `name` e `type` são obrigatórios no banco e não têm default — omiti-los grava valores vazios e quebra o cruzamento com transações feito por budget_comparison (que casa Transaction.type = Budget.type). Efeito colateral: recalcula analytics (cashflow/networth) e insights do usuário. Diferente de create_goal (meta de acúmulo) e create_debt (dívida a pagar).",
    method: "POST",
    path: "/api/budgets",
    input: {
      name: z.string().describe("Nome do orçamento (ex: 'Mercado de Janeiro')"),
      type: z.enum(["INCOME", "EXPENSE", "INVESTMENT"]).describe("Tipo — precisa bater com o Transaction.type das transações que devem contar para este orçamento"),
      category: z.string().optional().describe("Nome da categoria a limitar (deve bater com Transaction.category). Omitido ou 'ALL' = todas as categorias desse type"),
      amount: z.number().describe("Valor orçado/limite do período"),
      currency: z.string().optional().describe("Moeda (ISO 4217). Default: BRL"),
      period: z.enum(["MONTHLY", "YEARLY"]).optional().describe("Periodicidade. Sem default no banco: se omitido, o orçamento não casa com a regra MONTHLY em budget_comparison/budget_daily e acaba tratado como anual — prefira sempre informar"),
      year: z.number().int().describe("Ano do período (ex: 2026)"),
      month: z.number().int().optional().describe("Mês (1-12), obrigatório apenas quando period = MONTHLY"),
    },
    outputSchema: budgetShape,
  },
  {
    name: "update_budget",
    title: "Atualizar orçamento",
    description: "Atualiza um orçamento (parcial — campos omitidos ou string vazia mantêm o valor atual). Efeito colateral: recalcula analytics e insights do usuário, igual create_budget. Devolve apenas `{ count }`, não o orçamento atualizado.",
    method: "PUT",
    path: "/api/budgets/:id",
    input: {
      id: z.string().describe("Id do orçamento (Budget) a atualizar"),
      name: z.string().optional(),
      type: z.enum(["INCOME", "EXPENSE", "INVESTMENT"]).optional(),
      category: z.string().optional().describe("'ALL' para remover o filtro de categoria"),
      amount: z.number().optional(),
      currency: z.string().optional(),
      period: z.enum(["MONTHLY", "YEARLY"]).optional(),
      year: z.number().int().optional(),
      month: z.number().int().optional(),
    },
    outputSchema: countShape,
  },
  {
    name: "delete_budget",
    title: "Excluir orçamento",
    description: "Exclui um orçamento. Efeito colateral: recalcula analytics e insights do usuário. Não apaga nem desvincula as transações que eram comparadas contra ele.",
    method: "DELETE",
    path: "/api/budgets/:id",
    input: { id: z.string().describe("Id do orçamento (Budget) a excluir") },
    destructive: true,
    outputSchema: z.object({ count: z.number().optional(), success: z.boolean().optional() }),
  },
  {
    name: "budget_comparison",
    title: "Comparativo do orçamento",
    description: "Compara orçado (Budget.amount) vs gasto real de UM orçamento específico no seu período (mês, se MONTHLY; ano inteiro, se YEARLY), somando as transações do mesmo type/category no intervalo. Inclui `daily`: série diária acumulada do mês com projeção linear até o fim do mês (só para orçamentos MONTHLY do mês vigente — demais casos devolvem lista vazia). `id` é o id do Budget, não de uma categoria.",
    method: "GET",
    path: "/api/budgets/:id/comparison",
    input: { id: z.string().describe("Id do orçamento (Budget)") },
    readOnly: true,
    outputSchema: budgetComparisonShape,
  },

  {
    name: "list_debts",
    title: "Listar dívidas",
    description: "Lista as dívidas (Debt) do usuário, mais recentes primeiro — financiamentos, empréstimos, cartão de crédito parcelado fora do sistema de faturas, etc. `equityId`, quando presente, vincula a dívida a um ativo (Equity) financiado por ela, usado no cálculo de patrimônio líquido (valor do ativo - dívida).",
    method: "GET",
    path: "/api/debts",
    input: {},
    readOnly: true,
    outputSchema: z.object({ data: z.array(debtShape) }),
  },
  {
    name: "create_debt",
    title: "Criar dívida",
    description: "Registra uma dívida do usuário. Se `equityId` for informado, precisa pertencer ao usuário (validado antes de gravar — erro 400 'Invalid equityId' caso contrário) e representa o ativo financiado por essa dívida (ex: financiamento vinculado ao imóvel). Efeito colateral: recalcula analytics (patrimônio líquido) e insights do usuário.",
    method: "POST",
    path: "/api/debts",
    input: {
      name: z.string().describe("Nome/descrição da dívida (ex: 'Financiamento do carro')"),
      totalAmount: z.number().describe("Valor total original da dívida"),
      remainingAmount: z.number().optional().describe("Saldo devedor atual. Default: 0 se omitido — informe para não zerar a dívida por engano"),
      interestRate: z.number().optional().describe("Taxa de juros mensal em % (ex: 1.5 = 1.5% a.m.), usada para projetar o saldo devedor futuro"),
      dueDate: z.string().optional().describe("Data de vencimento (ISO)"),
      creditor: z.string().optional().describe("Nome do credor/instituição"),
      description: z.string().optional(),
      status: z.enum(["ACTIVE", "PAID", "OVERDUE"]).optional().describe("Default: ACTIVE"),
      currency: z.string().optional().describe("Moeda (ISO 4217). Default: BRL"),
      category: z.string().optional().describe("Categoria livre da dívida (ex: 'Financiamento', 'Empréstimo pessoal')"),
      equityId: z.string().optional().describe("Id de um Equity (investimento/ativo) do usuário financiado por esta dívida"),
    },
    outputSchema: debtShape,
  },
  {
    name: "update_debt",
    title: "Atualizar dívida",
    description: "Atualiza uma dívida (parcial — campo omitido ou string vazia mantém o atual; `status`/`category`/`creditor`/`description`/`currency` seguem essa mesma regra, não há como limpar um valor já preenchido por esta tool). `equityId`, se enviado, é revalidado contra o dono. Efeito colateral: recalcula analytics e insights do usuário.",
    method: "PUT",
    path: "/api/debts/:id",
    input: {
      id: z.string().describe("Id da dívida (Debt) a atualizar"),
      name: z.string().optional(),
      totalAmount: z.number().optional(),
      remainingAmount: z.number().optional().describe("Novo saldo devedor — use para registrar um pagamento parcial"),
      interestRate: z.number().optional().describe("Taxa de juros mensal em %"),
      dueDate: z.string().optional(),
      creditor: z.string().optional(),
      description: z.string().optional(),
      status: z.enum(["ACTIVE", "PAID", "OVERDUE"]).optional(),
      currency: z.string().optional(),
      category: z.string().optional(),
      equityId: z.string().optional().describe("Novo Equity vinculado; precisa pertencer ao usuário"),
    },
    outputSchema: countShape,
  },
  {
    name: "delete_debt",
    title: "Excluir dívida",
    description: "Exclui uma dívida. Efeito colateral: recalcula analytics (patrimônio líquido) e insights do usuário.",
    method: "DELETE",
    path: "/api/debts/:id",
    input: { id: z.string().describe("Id da dívida (Debt) a excluir") },
    destructive: true,
    outputSchema: countShape,
  },
  {
    name: "debt_payoff_plan",
    title: "Plano de quitação de dívida",
    description:
      "Simula a quitação de UMA dívida: informe targetMonths (quanto pagar por mês pra quitar em N meses) OU monthlyPayment (em quantos meses quita pagando R$X/mês) — nunca os dois. Devolve o valor mensal, total pago, juros totais e o impacto no saldo projetado (inclusive se cria mês no vermelho). Não grava nada, é só simulação — para efetivamente abater o saldo use update_debt (remainingAmount).",
    method: "GET",
    path: "/api/insights/debt-payoff-plan",
    input: {
      debtId: z.string().describe("id da dívida (ver list_debts)"),
      targetMonths: z.number().optional().describe("Quero quitar em N meses — devolve o valor mensal necessário"),
      monthlyPayment: z.number().optional().describe("Posso pagar R$X/mês — devolve em quantos meses quita"),
    },
    readOnly: true,
    outputSchema: z.object({
      debtId: z.string().optional(),
      debtName: z.string().optional(),
      remainingAmount: z.number().optional(),
      interestRatePct: z.number().optional(),
      monthlyPayment: z.number().optional(),
      months: z.number().optional(),
      totalPaid: z.number().optional(),
      totalInterest: z.number().optional(),
      projectedImpact: z
        .array(
          z.object({
            label: z.string().optional(),
            originalEndingBalance: z.number().optional(),
            newEndingBalance: z.number().optional(),
          }),
        )
        .optional(),
      newNegativeMonths: z.array(z.string()).optional(),
      text: z.string().optional(),
    }),
  },
];
