import { z } from "zod";
import type { ToolDef } from "../types.js";

export const goalBudgetDebtTools: ToolDef[] = [
  { name: "list_goals", title: "Listar metas", description: "Lista as metas financeiras do usuário.", method: "GET", path: "/api/goals", input: {}, readOnly: true },
  {
    name: "create_goal",
    title: "Criar meta",
    description: "Cria uma meta financeira.",
    method: "POST",
    path: "/api/goals",
    input: {
      name: z.string(),
      targetAmount: z.number(),
      currentAmount: z.number().optional(),
      targetDate: z.string().optional(),
      icon: z.string().optional(),
      color: z.string().optional(),
    },
  },
  {
    name: "update_goal",
    title: "Atualizar meta",
    description: "Atualiza uma meta (parcial).",
    method: "PUT",
    path: "/api/goals/:id",
    input: { id: z.string(), name: z.string().optional(), targetAmount: z.number().optional(), currentAmount: z.number().optional(), targetDate: z.string().optional() },
  },
  { name: "delete_goal", title: "Excluir meta", description: "Exclui uma meta.", method: "DELETE", path: "/api/goals/:id", input: { id: z.string() }, destructive: true },

  {
    name: "list_budgets",
    title: "Listar orçamentos",
    description: "Lista orçamentos do usuário, opcionalmente filtrando por ano/mês.",
    method: "GET",
    path: "/api/budgets",
    input: { year: z.string().optional(), month: z.string().optional() },
    readOnly: true,
  },
  {
    name: "create_budget",
    title: "Criar orçamento",
    description: "Cria um orçamento mensal por categoria.",
    method: "POST",
    path: "/api/budgets",
    input: { categoryId: z.string(), amount: z.number(), year: z.number().int(), month: z.number().int() },
  },
  {
    name: "update_budget",
    title: "Atualizar orçamento",
    description: "Atualiza um orçamento (parcial).",
    method: "PUT",
    path: "/api/budgets/:id",
    input: { id: z.string(), amount: z.number().optional() },
  },
  { name: "delete_budget", title: "Excluir orçamento", description: "Exclui um orçamento.", method: "DELETE", path: "/api/budgets/:id", input: { id: z.string() }, destructive: true },
  {
    name: "budget_comparison",
    title: "Comparativo do orçamento",
    description: "Compara orçado vs gasto real de um orçamento, com as transações da categoria no período.",
    method: "GET",
    path: "/api/budgets/:id/comparison",
    input: { id: z.string() },
    readOnly: true,
  },

  { name: "list_debts", title: "Listar dívidas", description: "Lista as dívidas do usuário.", method: "GET", path: "/api/debts", input: {}, readOnly: true },
  {
    name: "create_debt",
    title: "Criar dívida",
    description: "Registra uma dívida.",
    method: "POST",
    path: "/api/debts",
    input: {
      name: z.string(),
      totalAmount: z.number(),
      remainingAmount: z.number().optional(),
      interestRate: z.number().optional(),
      dueDate: z.string().optional(),
      creditor: z.string().optional(),
      equityId: z.string().optional(),
    },
  },
  {
    name: "update_debt",
    title: "Atualizar dívida",
    description: "Atualiza uma dívida (parcial — campo vazio mantém o atual).",
    method: "PUT",
    path: "/api/debts/:id",
    input: { id: z.string(), remainingAmount: z.number().optional(), interestRate: z.number().optional(), dueDate: z.string().optional() },
  },
  { name: "delete_debt", title: "Excluir dívida", description: "Exclui uma dívida.", method: "DELETE", path: "/api/debts/:id", input: { id: z.string() }, destructive: true },
];
