import { z } from "zod";
import type { ToolDef } from "../types.js";

export const insightTools: ToolDef[] = [
  {
    name: "cashflow_forecast",
    title: "Projeção de fluxo de caixa",
    description: "Projeção de fluxo de caixa (entradas/saídas/saldo) para os próximos meses.",
    method: "GET",
    path: "/api/cashflow/forecast",
    input: {},
    readOnly: true,
  },
  {
    name: "spending_projection",
    title: "Projeção de gastos",
    description: "Projeção de gastos por categoria com base no histórico.",
    method: "GET",
    path: "/api/analytics/spending-projection",
    input: {},
    readOnly: true,
  },
  {
    name: "networth_projection",
    title: "Projeção de patrimônio líquido",
    description: "Projeção de evolução do patrimônio líquido (ativos - dívidas).",
    method: "GET",
    path: "/api/analytics/networth-projection",
    input: {},
    readOnly: true,
  },
  {
    name: "current_month_spending",
    title: "Gastos do mês atual",
    description: "Resumo dos gastos do mês corrente por categoria.",
    method: "GET",
    path: "/api/analytics/current-month-spending",
    input: {},
    readOnly: true,
  },
  {
    name: "categories_insights",
    title: "Insights por categoria",
    description: "Gasto acumulado por categoria (com subcategorias) e comparação com orçamento.",
    method: "GET",
    path: "/api/categories/insights",
    input: {},
    readOnly: true,
  },
  {
    name: "insights_highlight",
    title: "Destaque financeiro do mês",
    description: "Highlight textual gerado a partir da movimentação financeira do mês.",
    method: "GET",
    path: "/api/insights/highlight",
    input: {},
    readOnly: true,
  },
  {
    name: "behavior_insights",
    title: "Insights de comportamento",
    description: "Análise de padrões de comportamento financeiro (gastos recorrentes, anomalias, etc).",
    method: "GET",
    path: "/api/insights/behavior",
    input: {},
    readOnly: true,
  },
  {
    name: "list_tags",
    title: "Listar tags",
    description: "Lista as tags usadas para marcar transações.",
    method: "GET",
    path: "/api/tags",
    input: {},
    readOnly: true,
  },
  {
    name: "tags_insights",
    title: "Insights por tag",
    description: "Agregação mensal de gastos por tag.",
    method: "GET",
    path: "/api/tags/insights",
    input: {},
    readOnly: true,
  },
  {
    name: "create_tag",
    title: "Criar tag",
    description: "Cria uma nova tag.",
    method: "POST",
    path: "/api/tags",
    input: { name: z.string(), color: z.string().optional() },
  },
];
