import { z } from "zod";
import type { ToolDef } from "../types.js";

export const transactionTools: ToolDef[] = [
  {
    name: "list_transactions",
    title: "Listar transações",
    description: "Lista todas as transações do usuário, com conta/categoria/tags incluídas.",
    method: "GET",
    path: "/api/transactions",
    input: {},
    readOnly: true,
  },
  {
    name: "upcoming_transactions",
    title: "Próximas transações",
    description: "Lista transações dos próximos dias (agendadas/pendentes) com resumo.",
    method: "GET",
    path: "/api/transactions/upcoming",
    input: {
      from: z.string().optional().describe("Data ISO início, default hoje"),
      to: z.string().optional().describe("Data ISO fim, default +30 dias"),
      status: z.enum(["pending", "paid", "all"]).optional(),
    },
    readOnly: true,
  },
  {
    name: "create_transaction",
    title: "Criar transação",
    description:
      "Cria uma transação (expense/income/transfer). Requer accountId ou cardId. Valida saldo/limite disponível.",
    method: "POST",
    path: "/api/transactions",
    input: {
      type: z.enum(["EXPENSE", "INCOME", "TRANSFER"]),
      amount: z.number(),
      description: z.string(),
      date: z.string().describe("Data ISO ou dd/mm/yyyy"),
      categoryId: z.string().optional(),
      accountId: z.string().optional(),
      cardId: z.string().optional(),
      destinationAccountId: z.string().optional().describe("Obrigatório para TRANSFER"),
      goalId: z.string().optional(),
      equityId: z.string().optional(),
      costCenterId: z.string().optional(),
      agentId: z.string().optional(),
      installments: z.number().int().optional().describe("Número de parcelas (cartão)"),
      scheduledDate: z.string().optional().describe("Se futura, agenda sem tocar saldo"),
      isPaid: z.boolean().optional(),
      paidDate: z.string().optional(),
      nature: z.string().optional(),
      ticker: z.string().optional().describe("Ticker do ativo, para transação de investimento"),
      exchange: z.string().optional(),
      shares: z.number().optional(),
    },
  },
  {
    name: "confirm_new_transaction",
    title: "Criar transação já confirmada",
    description: "Mesmo que create_transaction, mas sem checar saldo (permite saldo negativo).",
    method: "POST",
    path: "/api/transactions/confirm",
    input: {
      type: z.enum(["EXPENSE", "INCOME", "TRANSFER"]),
      amount: z.number(),
      description: z.string(),
      date: z.string(),
      categoryId: z.string().optional(),
      accountId: z.string().optional(),
      cardId: z.string().optional(),
      destinationAccountId: z.string().optional(),
      goalId: z.string().optional(),
      equityId: z.string().optional(),
      costCenterId: z.string().optional(),
      confirmNegativeBalance: z.boolean().optional(),
    },
  },
  {
    name: "confirm_pending_transaction",
    title: "Confirmar transação pendente",
    description: "Marca uma transação existente como paga e aplica o efeito no saldo.",
    method: "POST",
    path: "/api/transactions/:id/confirm",
    input: { id: z.string() },
  },
  {
    name: "update_transaction",
    title: "Atualizar transação",
    description: "Atualiza uma transação (parcial). Reverte e reaplica o efeito de saldo se amount/type/accountId mudarem.",
    method: "PUT",
    path: "/api/transactions/:id",
    input: {
      id: z.string(),
      type: z.string().optional(),
      amount: z.number().optional(),
      description: z.string().optional(),
      date: z.string().optional(),
      categoryId: z.string().optional(),
      accountId: z.string().optional(),
      cardId: z.string().optional(),
      isPaid: z.boolean().optional(),
      paidDate: z.string().optional(),
    },
  },
  {
    name: "delete_transaction",
    title: "Excluir transação",
    description: "Exclui uma transação e reverte seu efeito no saldo/fatura/meta se estava paga.",
    method: "DELETE",
    path: "/api/transactions/:id",
    input: { id: z.string() },
    destructive: true,
  },
];
